-- room-cli feedback table. Run once in the Supabase SQL editor.
-- The CLI ships only the publishable key, which can insert reports and nothing else.

create table public.feedback (
  id          uuid primary key,                 -- generated by the CLI; a retried report is a no-op
  created_at  timestamptz not null default now(),
  kind        text not null check (kind in ('bug', 'advice')),
  reporter    text,                             -- claude, codex, human
  tool        text,                             -- claude-code, codex, shell
  version     text,                             -- room --version
  os          text,                             -- linux, wsl
  project     text,                             -- only with --project / --room
  room        text,                             -- only with --room
  message     text not null check (char_length(message) <= 8000),
  context     text check (char_length(context) <= 8000)   -- only with --context
);

alter table public.feedback enable row level security;

-- Grants first: an RLS policy alone does not grant the privilege.
revoke all on table public.feedback from anon, authenticated;
grant insert on table public.feedback to anon;

create policy "anon can insert feedback"
  on public.feedback for insert to anon with check (true);

-- No select, update or delete policy for anon: reports are write-only from the CLI.
